-- Question 4: Revenue by Specialty & Month
-- Goal: Calculate the total revenue (allowed_amount) generated by each specialty per month.

SELECT
    -- 1. Month
    DATE_FORMAT(e.encounter_date, '%Y-%m') AS month,

-- 2. Specialty
s.specialty_name,

-- 3. Total Revenue
SUM(b.allowed_amount) AS total_revenue FROM billing b

-- Join chain: Billing -> Encounter -> Provider -> Specialty
JOIN encounters e ON b.encounter_id = e.encounter_id
JOIN providers p ON e.provider_id = p.provider_id
JOIN specialties s ON p.specialty_id = s.specialty_id
GROUP BY
    1,
    2
ORDER BY month, total_revenue DESC;